### PR TITLE
Bitbucket cloud build status update

### PR DESCRIPTION
**Pull request by HBarnabas**
This change is [Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)

### CODE REVIEW

**Review by miklosn — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)* status: 2 of 5 files reviewed, 8 unresolved discussions (waiting on @akissds and @HBarnabas)

___
*[bitbucket-cloud-build-status-update/cloud-function.tf, line 28 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2mUBr0zE546aSANSh:-Mo2mUBr0zE546aSANSi:b-hj4li2) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/cloud-function.tf#L28)):*
> ```HCL
>   runtime     = var.function_runtime
>   description = var.function_description
> ```

region?
___
*[bitbucket-cloud-build-status-update/cloud-function.tf, line 57 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2mbTqD286Mt9gdu3s:-Mo2mbTqD286Mt9gdu3t:b-hj4li2) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/cloud-function.tf#L57)):*
> ```HCL
>   project      = var.project_id
>   name         = var.topic_name
> }
> ```

region?
___
*[bitbucket-cloud-build-status-update/cloud-function.tf, line 63 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2ljKH2C9OxwIa6X00:-Mo2ljKH2C9OxwIa6X01:bapq69r) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/cloud-function.tf#L63)):*
> ```HCL
>   name        = var.logsink_name
>   destination = "pubsub.googleapis.com/projects/${var.project_id}/topics/${google_pubsub_topic.build_logs.name}"
>   filter      = "resource.type = \"build\" labels.build_step = \"MAIN\" textPayload : (\"starting build\" OR (\"DONE\" OR \"ERROR\")) labels.build_tags : \"trigger\""
> ```

What if i have stuff from multiple bitbucket repos building in the same project?
___
*[bitbucket-cloud-build-status-update/README.md, line 5 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2hzH7EiDgr7pSngpr:-Mo2hzH80AeE-wJjhYVS:b-o98nn4) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/README.md#L5)):*
> ```Markdown
> ## Overview
> 
> This terraform module create several resources which will be used to automate the Cloud Build status response to the Bitbucket API.
> ```

As a user, might be good to get a summary on what's going on, "create several resources" doesn't tell much, have to read the code to learn that it uses a logging sink to trigger a function which posts to Bitbucket.
___
*[bitbucket-cloud-build-status-update/README.md, line 69 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2kuCB26x_7GHQVLgL:-Mo2kuCB26x_7GHQVLgM:bmirapg) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/README.md#L69)):*
> ```Markdown
> | <a name="input_function_runtime"></a> [function\_runtime](#input\_function\_runtime) | The runtime in which the function is going to run. | `string` | `"python39"` | no |
> | <a name="input_project_id"></a> [project\_id](#input\_project\_id) | Project ID where this stack should be deployed | `string` | n/a | yes |
> | <a name="input_topic_name"></a> [topic\_name](#input\_topic\_name) | PubSub Topic Name for Cloud Scheduler to post scheduler data which will trigger Cloud Function | `string` | n/a | yes |
> ```

Cloud Scheduler?
___
*[bitbucket-cloud-build-status-update/variables.tf, line 11 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2mgWx-urdwig4MBBY:-Mo2mgWx-urdwig4MBBZ:b-fjovn2) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/variables.tf#L11)):*
> ```HCL
>   type = string
>   description = "Cloud Storage Bucket location to store Cloud Function source code."
> }
> ```

internal implementation detail. instead, expect a single location parameter and use it everywhere
___
*[bitbucket-cloud-build-status-update/variables.tf, line 15 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2j57bA08rXubQ0dWA:-Mo2j57bA08rXubQ0dWB:b-tw20ra) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/variables.tf#L15)):*
> ```HCL
> #PubSub
> variable "topic_name" {
>   type = string
> ```

Some of these are confusing from a user perspective. topic name, bucket name, logsink name, function name.. why do i have to provide these?

Suggest a rethink of this approach, the variables define the interface of the solution.
___
*[bitbucket-cloud-build-status-update/variables.tf, line 64 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2mB6sCsTw1vuSLAQF:-Mo2mB6sCsTw1vuSLAQG:b-2xv648) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/variables.tf#L64)):*
> ```HCL
>   type = string
>   description = "Bitbucket password for user auth."
> }
> ```

Maybe accept a reference to a Secret Manager secret for the username+password

**Review by gabor-farkas — COMMENTED** [review]
> Reviewed 5 of 5 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)* status: all files reviewed, 8 unresolved discussions (waiting on @akissds and @HBarnabas)

**Review by akissds — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)* status: 1 of 5 files reviewed, 10 unresolved discussions (waiting on @gabor-farkas and @HBarnabas)

___
*[bitbucket-cloud-build-status-update/cloud-function.tf, line 78 at r17](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mod7Fkh2S_-cQQnC0O9:-Mod7Fkh2S_-cQQnC0OA:brp3cxb) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1743957622c36140f1aea4cdaef45c28d9f9fccd/bitbucket-cloud-build-status-update/cloud-function.tf#L78)):*
> ```HCL
> }
> 
> resource "google_secret_manager_secret" "bitbucket_secret" {
> ```

The secret should be an external parameter. See data blocks
The secret's project id could be a parameter. 
___
*[bitbucket-cloud-build-status-update/scripts/main.py, line 35 at r17](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mod7fRXEIRrCAdUvQeW:-Mod7fRXEIRrCAdUvQeX:bnf57cc) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1743957622c36140f1aea4cdaef45c28d9f9fccd/bitbucket-cloud-build-status-update/scripts/main.py#L35)):*
> ```Python
>   return auth['access_token']
> 
> def buildStat(event, *content):
> ```

Probably you have to pass the secret parameters.

**Review by akissds — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)* status: 1 of 5 files reviewed, 10 unresolved discussions (waiting on @gabor-farkas, @HBarnabas, and @miklosn)

___
*[bitbucket-cloud-build-status-update/cloud-function.tf, line 63 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2ljKH2C9OxwIa6X00:-ModBFOI-KE-1NxXBp4u:b-udqniw) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/cloud-function.tf#L63)):*
<details><summary><i>Previously, miklosn (Miklos Niedermayer) wrote…</i></summary><blockquote>

What if i have stuff from multiple bitbucket repos building in the same project?
</blockquote></details>

Pls. check what happens if the repo name has an underscore character.

**Review by gabor-farkas — COMMENTED** [review]
> Reviewed 4 of 4 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)* status: all files reviewed, 10 unresolved discussions (waiting on @HBarnabas and @miklosn)

**Review by gabor-farkas — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)* status: 3 of 5 files reviewed, 11 unresolved discussions (waiting on @gabor-farkas, @HBarnabas, and @miklosn)

___
*[bitbucket-cloud-build-status-update/variables.tf, line 57 at r18](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mp5gCxUBExAKDZHscNp:-Mp5gCxUBExAKDZHscNq:bggoqim) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/0ee8bd6d1694c618f16cab7a19a902ea0b7e9820/bitbucket-cloud-build-status-update/variables.tf#L57)):*
> ```HCL
> 
> # function environmental variables
> variable "bitbucket_secret_id" {
> ```

why not accept the fully qualified secret version id as an input?

**Review by gabor-farkas — COMMENTED** [review]
> Reviewed 1 of 4 files at r18.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)* status: 4 of 5 files reviewed, 11 unresolved discussions (waiting on @gabor-farkas, @HBarnabas, and @miklosn)

**Review by HBarnabas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)* status: 3 of 5 files reviewed, 11 unresolved discussions (waiting on @akissds, @gabor-farkas, and @miklosn)

___
*[bitbucket-cloud-build-status-update/cloud-function.tf, line 28 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2mUBr0zE546aSANSh:-MoiZBUJ9z9aiOLbewXm:bdwxhat) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/cloud-function.tf#L28)):*
<details><summary><i>Previously, miklosn (Miklos Niedermayer) wrote…</i></summary><blockquote>

region?
</blockquote></details>

add region to function
___
*[bitbucket-cloud-build-status-update/cloud-function.tf, line 57 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2mbTqD286Mt9gdu3s:-MoiZljQAjBc_HV5ueUX:b-iyuq4d) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/cloud-function.tf#L57)):*
<details><summary><i>Previously, miklosn (Miklos Niedermayer) wrote…</i></summary><blockquote>

region?
</blockquote></details>

topic and sink resource has no region field
___
*[bitbucket-cloud-build-status-update/cloud-function.tf, line 63 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2ljKH2C9OxwIa6X00:-MqtGFsQCjMS6wGQESh4:bian4a2) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/cloud-function.tf#L63)):*
<details><summary><i>Previously, akissds wrote…</i></summary><blockquote>

Pls. check what happens if the repo name has an underscore character.
</blockquote></details>

multiple repos build logs doesn't matter, becouse for the API a combination IDs has to match and only the right one will be accepted
cannot depend on parsing strings from the response, becouse it doesn't differentiates between in-string underscore and joining underscore
___
*[bitbucket-cloud-build-status-update/cloud-function.tf, line 78 at r17](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mod7Fkh2S_-cQQnC0O9:-Moia3c89es8t_O1jdv4:b-mdsqba) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1743957622c36140f1aea4cdaef45c28d9f9fccd/bitbucket-cloud-build-status-update/cloud-function.tf#L78)):*
<details><summary><i>Previously, akissds wrote…</i></summary><blockquote>

The secret should be an external parameter. See data blocks
The secret's project id could be a parameter. 
</blockquote></details>

replaced secret manager resource with data
___
*[bitbucket-cloud-build-status-update/README.md, line 5 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2hzH7EiDgr7pSngpr:-MqtLROf9PBgmpMG6403:b-mn7jyl) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/README.md#L5)):*
<details><summary><i>Previously, miklosn (Miklos Niedermayer) wrote…</i></summary><blockquote>

As a user, might be good to get a summary on what's going on, "create several resources" doesn't tell much, have to read the code to learn that it uses a logging sink to trigger a function which posts to Bitbucket.
</blockquote></details>

Updated description with a list of created resources.
___
*[bitbucket-cloud-build-status-update/README.md, line 69 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2kuCB26x_7GHQVLgL:-MoiXtg28VmbIX8ce5qy:bt5bpvd) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/README.md#L69)):*
<details><summary><i>Previously, miklosn (Miklos Niedermayer) wrote…</i></summary><blockquote>

Cloud Scheduler?
</blockquote></details>

Generated correct readme with pre-commit.
___
*[bitbucket-cloud-build-status-update/variables.tf, line 11 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2mgWx-urdwig4MBBY:-Moi_0Qp2p077l91C9ut:bfppono) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/variables.tf#L11)):*
<details><summary><i>Previously, miklosn (Miklos Niedermayer) wrote…</i></summary><blockquote>

internal implementation detail. instead, expect a single location parameter and use it everywhere
</blockquote></details>

unified location variable
___
*[bitbucket-cloud-build-status-update/variables.tf, line 15 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2j57bA08rXubQ0dWA:-Moi_Bnz-4PoJYlKMP0N:bko5jye) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/variables.tf#L15)):*
<details><summary><i>Previously, miklosn (Miklos Niedermayer) wrote…</i></summary><blockquote>

Some of these are confusing from a user perspective. topic name, bucket name, logsink name, function name.. why do i have to provide these?

Suggest a rethink of this approach, the variables define the interface of the solution.
</blockquote></details>

updated resource names with generated id
___
*[bitbucket-cloud-build-status-update/variables.tf, line 64 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2mB6sCsTw1vuSLAQF:-Moi_YJd4NYB-Cl6lLU1:b-20gvgo) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/variables.tf#L64)):*
<details><summary><i>Previously, miklosn (Miklos Niedermayer) wrote…</i></summary><blockquote>

Maybe accept a reference to a Secret Manager secret for the username+password
</blockquote></details>

updated with secret manager reference
___
*[bitbucket-cloud-build-status-update/variables.tf, line 57 at r18](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mp5gCxUBExAKDZHscNp:-MqtNeKeENXDcTu31ekM:bs32f36) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/0ee8bd6d1694c618f16cab7a19a902ea0b7e9820/bitbucket-cloud-build-status-update/variables.tf#L57)):*
<details><summary><i>Previously, gabor-farkas wrote…</i></summary><blockquote>

why not accept the fully qualified secret version id as an input?
</blockquote></details>

could do that, but it would be a hassle to parse it for the "google_secret_manager_secret_iam_binding" recourse
should i do it nevertheless?
___
*[bitbucket-cloud-build-status-update/scripts/main.py, line 35 at r17](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mod7fRXEIRrCAdUvQeW:-MqtOdQHBevs6xRI2lzj:b-896fix) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1743957622c36140f1aea4cdaef45c28d9f9fccd/bitbucket-cloud-build-status-update/scripts/main.py#L35)):*
<details><summary><i>Previously, akissds wrote…</i></summary><blockquote>

Probably you have to pass the secret parameters.
</blockquote></details>

Done.

**Review by gabor-farkas — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r18, 1 of 1 files at r19, all commit messages.
> Dismissed @akissds and @miklosn from 9 discussions.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)* status: all files reviewed, 3 unresolved discussions (waiting on @HBarnabas and @miklosn)

___
*[bitbucket-cloud-build-status-update/README.md, line 5 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2hzH7EiDgr7pSngpr:-Mqy_54l2H0IDrYhCqtg:b-wqcljl) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/README.md#L5)):*
<details><summary><i>Previously, HBarnabas wrote…</i></summary><blockquote>

Updated description with a list of created resources.
</blockquote></details>

A kind of a human readable summary of the solution would be useful here, eg:


The purpose of this module is to let a Bitbucket-based Cloud Build pipeline report build status to Bitbucket. This feature is automatically provided for Github by the Cloud Build Github app, but there's no such feature (at least yet) for Bitbucket.

The solution relies on the logs written by Cloud Build to Cloud Logging to detect certain build events. In case of such an event, a python script running in Cloud Function will check the build on the Cloud Build API and then do the reporting to Bitbucket over its API.

To authenticate the requests to Bitbucket, you need to follow the steps _"Client Credentials Grant (4.4)"_ part from https://developer.atlassian.com/cloud/bitbucket/oauth-2/ to create an OAuth consumer, for example by navigating to `https://bitbucket.org/<<YOUR ORG NAME>>/workspace/settings/oauth-consumers/new` and then store the available "Key" and "Secret" values in Secret Manager, providing the secret ids to this module. The module will try to grant access to the secrets for the Cloud Functions service account.
___
*[bitbucket-cloud-build-status-update/variables.tf, line 11 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2mgWx-urdwig4MBBY:-MqybEP083Lv9yFjfLnR:bu6kkdd) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/variables.tf#L11)):*
<details><summary><i>Previously, HBarnabas wrote…</i></summary><blockquote>

unified location variable
</blockquote></details>

It's not really a "project location" - there's no such term as a project location after all - we can name this resource_location, or rather just "location", it's quite common to use such a variable.
The description is also a bit inaccurate this way, because this location is not only for the storage bucket, but also for the cloud functions region. - and actually this means that we shouldn't name this 'location'. By location we generally mean "zone or region", but for cloud functions, you need to specific a region, it won't accept a zone (while GCS would), so we can rather just name this variable `region` to make it explicit that only a region will be accepted.
___
*[bitbucket-cloud-build-status-update/variables.tf, line 57 at r18](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mp5gCxUBExAKDZHscNp:-MqyYPvG8bi2Le3_iNUU:b9v2qsj) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/0ee8bd6d1694c618f16cab7a19a902ea0b7e9820/bitbucket-cloud-build-status-update/variables.tf#L57)):*
<details><summary><i>Previously, HBarnabas wrote…</i></summary><blockquote>

could do that, but it would be a hassle to parse it for the "google_secret_manager_secret_iam_binding" recourse
should i do it nevertheless?
</blockquote></details>

I'd vote for doing it, it's much simpler to pass on the fully qualified name. (regexp is fun :) )

**Review by HBarnabas — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @gabor-farkas and @miklosn)

___
*[bitbucket-cloud-build-status-update/README.md, line 5 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2hzH7EiDgr7pSngpr:-Mr6uEBm6EkwlTWAAMqa:b-ojwm3l) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/README.md#L5)):*
<details><summary><i>Previously, gabor-farkas wrote…</i></summary><blockquote>

A kind of a human readable summary of the solution would be useful here, eg:


The purpose of this module is to let a Bitbucket-based Cloud Build pipeline report build status to Bitbucket. This feature is automatically provided for Github by the Cloud Build Github app, but there's no such feature (at least yet) for Bitbucket.

The solution relies on the logs written by Cloud Build to Cloud Logging to detect certain build events. In case of such an event, a python script running in Cloud Function will check the build on the Cloud Build API and then do the reporting to Bitbucket over its API.

To authenticate the requests to Bitbucket, you need to follow the steps _"Client Credentials Grant (4.4)"_ part from https://developer.atlassian.com/cloud/bitbucket/oauth-2/ to create an OAuth consumer, for example by navigating to `https://bitbucket.org/<<YOUR ORG NAME>>/workspace/settings/oauth-consumers/new` and then store the available "Key" and "Secret" values in Secret Manager, providing the secret ids to this module. The module will try to grant access to the secrets for the Cloud Functions service account.

</blockquote></details>

true, and since you took the time to write such a detailed description, it would be a waste not to use it, thank you
___
*[bitbucket-cloud-build-status-update/variables.tf, line 11 at r15](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mo2mgWx-urdwig4MBBY:-Mr6tT-UC_2Jg0qIwM2S:bukawa9) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/1b4a3c629e46cdf4c889f429f7c7777f90d0568b/bitbucket-cloud-build-status-update/variables.tf#L11)):*
<details><summary><i>Previously, gabor-farkas wrote…</i></summary><blockquote>

It's not really a "project location" - there's no such term as a project location after all - we can name this resource_location, or rather just "location", it's quite common to use such a variable.
The description is also a bit inaccurate this way, because this location is not only for the storage bucket, but also for the cloud functions region. - and actually this means that we shouldn't name this 'location'. By location we generally mean "zone or region", but for cloud functions, you need to specific a region, it won't accept a zone (while GCS would), so we can rather just name this variable `region` to make it explicit that only a region will be accepted.
</blockquote></details>

noted, renamed `project_location` to `region`
___
*[bitbucket-cloud-build-status-update/variables.tf, line 57 at r18](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8#-Mp5gCxUBExAKDZHscNp:-Mr6tzZU2md2qvKydw8-:bb7f2mf) ([raw file](https://github.com/aliz-ai/terraform-aliz-modules/blob/0ee8bd6d1694c618f16cab7a19a902ea0b7e9820/bitbucket-cloud-build-status-update/variables.tf#L57)):*
<details><summary><i>Previously, gabor-farkas wrote…</i></summary><blockquote>

I'd vote for doing it, it's much simpler to pass on the fully qualified name. (regexp is fun :) )
</blockquote></details>

done

**Review by gabor-farkas — APPROVED** [review]
> Reviewed 3 of 3 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)* status: all files reviewed, 1 unresolved discussion (waiting on @miklosn)

**Review by gabor-farkas — APPROVED** [review]
> Dismissed @miklosn from a discussion.
> *[Reviewable](https://reviewable.io/reviews/aliz-ai/terraform-aliz-modules/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @HBarnabas)

**Pull request merged**
